### ISSUE TITLE
Tracker initialization difference between objective-c structure SDK

### ISSUE THREAD

**Issue by cclaan** [n6xej/RRStructureScannerSwift5#2]
Thanks for posting this project , it's been a good way to learn about the structure SDK. 
This is more of a question, so feel free to close... 
When calling 'enterScanningState' you initialize the tracker using the following code:
`_slamState.tracker!.initialCameraPose = _slamState.cameraPoseInitializer!.lastOutput.cameraPose`
[link to that line](https://github.com/n6xej/RRStructureScannerSwift5/blob/master/RRStructureScanner/Scanner/ViewController.swift#L473)
If i understand correctly, the cameraPoseInitializer 'cameraPose' uses a color registered depth frame so that pose would be for the color camera. In the objective-c structure SDK, they initialize the tracker with the following code:
`_slamState.tracker.initialCameraPose = _slamState.initialDepthCameraPose;`
Which seems to be the depth camera pose. Is there any reason yours is different? 
Thanks

**Comment by n6xej** [comment]
When using hardware registration they are the same. Hardware registration has been deprecated, but it was used in the original Swift port.

**Comment by cclaan** [comment]
Gotcha, thanks.
